version: '3.8'
services:
  mongo:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=blog
    ports:
      - "27017:27017"
    command: ["--bind_ip_all"]

  api:
    build: .
    ports:
      - "3001:8080"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/blog?authSource=admin
      - JWT_SECRET=un_secret_tres_long
      - PORT=8080
    depends_on:
      - mongo 