name: CI on Dispatch

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Message
        run: echo "Dispatch reçu, job simple exécuté (en attente de tests)" 