name: CI on Dispatch

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Exemple d'étapes build/test pour Node.js
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test 